### ISSUE TITLE
autoarchive shows twice on page

### ISSUE THREAD

**Issue by tonybaldwin** [dokufreaks/plugin-blog#65]
I've tried to use the autoarchive tag to place an archive below entries.
When I do so, the archive part is displayed twice.
I'm using Release 2014-05-05 "Ponder Stibbons" on a Debian Wheezy server, with php5,
blog plugin installed today (30 Dec 2014).

When I put the archive on its own page, it only displays once, just when I try to place it below entries on the same page do I see it displayed twice.

**Comment by michitux** [comment]
Yes, recursive includes are possible, but the recursion stops after one step. The blog plugin has a configuration option for explicitly excluding pages from blog listings which appears in the configuration manager but doesn't seem to be documented. You could use something like `!^log:.*:start$!` in order to exclude all `start` pages from the blog listing.

**Comment by michitux** [comment]
I've just documented the exclude feature and mentioned the possible duplication in the documentation.
