### ISSUE TITLE
May I acquire previous tarball? Update hosed customizations

### ISSUE THREAD

**Issue by tonybaldwin** [dokufreaks/plugin-blog#76]
Is there a way to acquire the master tarball from June?
I had updated then and all was good, but I updated today to the latest and my customizations to the blog index page got completely hosed.
Not even sure if rolling back will help, frankly, but the customizations were a good days work to get just right, and I've lost any relevant backups due to a hiccough with my dreamhost bucket to which I auto-upload tarzipped backups of my webroot. I've got nothing, because I autodelete after a week from the archives I keep on hand to keep them from piling up too deep, thinking I have the latest stored in the DHbucket.
Went from this: http://tonybaldwin.me/images/oldjournalindex.jpg
to this: http://tonybaldwin.me/images/journalindexafterupdate.jpg
very upsetting...
I really should have submitted some of those modifications in a pull request.
Honestly, the flat, single-column display you have is ugly and just makes no real sense for any blog from a design perspective (absolutely no offense intended).
Basically, I'd just moved the archive section to the right, which makes more sense, visually, and added a couple things (link and photo, as shown in above screenshot).
Should be simple to re-implement, but I have a brain tumor now, which I didn't have when I did that stuff, and everything is more difficult now...I'm exhausted and easily confused now, from meds and radiation...
Probably the old tarball won't help, either, but I'd like to give it a shot.
I probably made alterations in the plugin's style.css, which won't be reflected in your tarball, since my own DW template is apparently not the source of my modifications, but I don't recall what I changed where at all.
Some of it was in the php/html to add the photo and link and that part's easy enough, but moving the archive list to the right must have been in some css file somewhere, not sure where now, but I remember it was a PITA getting it to work as I wanted.
Rolling back revisions on the page makes no difference since the mod/customizations were clearly in other files.
Wish I had those backups, but you can't help me with that...that's entirely my fault for not being more careful about monitoring that stuff.
Brain cancer doesn't help...

**Comment by michitux** [comment]
You can get previous archives, but I've had a look at the history since June and the only changes were translation updates. For example [this archive](https://github.com/dokufreaks/plugin-blog/archive/bcf39caccc04c9477a5587871821227ee848df26.zip) contains the version after the changes from June 4th.

Concerning your screenshots I have the impression that you could achieve this by putting the archive syntax in a sidebar page and the regular blog syntax in the main page. As far as I know this archive page was never intended as the main page but rather as a monthly archive for getting a table of old posts of that month.

I'm sorry to hear that you have brain cancer, I wish you good luck with your brain tumor and hope that the treatment you get is effective against the tumor!

**Comment by tonybaldwin** [comment]
I thank you for your attention, suggestions, and concern for my health.
